name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          set -e  #VERY IMPORTANT (fails fast if error)

          cd ~/image_bg_removal_backend

          echo "Pulling latest code..."
          git pull origin main

          echo "Activating virtualenv..."
          source venv/bin/activate

          echo "Installing dependencies..."
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "Migrating database..."
          python manage.py migrate

          echo "Collecting static..."
          python manage.py collectstatic --noinput

          echo "Restarting services..."
          sudo supervisorctl restart all

          echo "Deployment completed successfully "

          EOF